export type Urun = {
  id: number;
  marka: string;
  model: string;
  modelYili: string;
  guc: string;
  saat: string;
  vites: string;
  kuyrukMili: string;
  kaldirmaKapasitesi: string;
  durum: "Sıfır" | "2. El";
  renk: string;
  textColor: string;
  badge: string;
  fotolar: string[];
  fiyat?: number;
};

export const urunler: Urun[] = [
  {
    id: 4,
    marka: "Erkunt",
    model: "Servet 80T",
    modelYili: "2007",
    guc: "80 HP",
    saat: "-",
    vites: "16+8",
    kuyrukMili: "540 d/d",
    kaldirmaKapasitesi: "3.200 kg",
    durum: "2. El",
    renk: "bg-teal-50",
    textColor: "text-teal-700",
    badge: "",
    fotolar: [
      "/tractors/erkunt-80t-2.webp",
      "/tractors/erkunt-80t-1.webp",
      "/tractors/erkunt-80t-3.webp",
      "/tractors/erkunt-80t-4.webp",
      "/tractors/erkunt-80t-5.webp",
      "/tractors/erkunt-80t-6.webp",
      "/tractors/erkunt-80t-7.webp",
      "/tractors/erkunt-80t-8.webp",
      "/tractors/erkunt-80t-9.webp",
      "/tractors/erkunt-80t-10.webp",
      "/tractors/erkunt-80t-11.webp",
      "/tractors/erkunt-80t-12.webp",
    ],
  },
  {
    id: 5,
    marka: "Massey Ferguson",
    model: "5430",
    modelYili: "2012",
    guc: "92 HP",
    saat: "6.000 saat",
    vites: "16+16",
    kuyrukMili: "540 / 540E / 1000 d/d",
    kaldirmaKapasitesi: "4.300 kg",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf5430-1.webp",
      "/tractors/mf5430-2.webp",
      "/tractors/mf5430-3.webp",
      "/tractors/mf5430-4.webp",
      "/tractors/mf5430-5.webp",
      "/tractors/mf5430-6.webp",
      "/tractors/mf5430-7.webp",
      "/tractors/mf5430-8.webp",
      "/tractors/mf5430-9.webp",
    ],
  },
  {
    id: 6,
    marka: "Başak",
    model: "2090S",
    modelYili: "2018",
    guc: "92 HP",
    saat: "-",
    vites: "24+24",
    kuyrukMili: "540 / 540E d/d",
    kaldirmaKapasitesi: "3.000 kg",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak2090s-1.webp",
      "/tractors/basak2090s-2.webp",
      "/tractors/basak2090s-3.webp",
      "/tractors/basak2090s-4.webp",
      "/tractors/basak2090s-5.webp",
      "/tractors/basak2090s-6.webp",
      "/tractors/basak2090s-7.webp",
      "/tractors/basak2090s-8.webp",
      "/tractors/basak2090s-9.webp",
      "/tractors/basak2090s-10.webp",
      "/tractors/basak2090s-11.webp",
      "/tractors/basak2090s-12.webp",
    ],
  },
  {
    id: 7,
    marka: "New Holland",
    model: "TD5.100",
    modelYili: "2022",
    guc: "100 HP",
    saat: "768 saat",
    vites: "12+12",
    kuyrukMili: "540 / 540E d/d",
    kaldirmaKapasitesi: "3.565 kg",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/nh-td5100-12.webp",
      "/tractors/nh-td5100-18.webp",
      "/tractors/nh-td5100-19.webp",
      "/tractors/nh-td5100-17.webp",
      "/tractors/nh-td5100-16.webp",
      "/tractors/nh-td5100-14.webp",
      "/tractors/nh-td5100-15.webp",
      "/tractors/nh-td5100-13.webp",
      "/tractors/nh-td5100-7.webp",
      "/tractors/nh-td5100-8.webp",
      "/tractors/nh-td5100-9.webp",
      "/tractors/nh-td5100-2.webp",
      "/tractors/nh-td5100-3.webp",
      "/tractors/nh-td5100-4.webp",
      "/tractors/nh-td5100-5.webp",
      "/tractors/nh-td5100-6.webp",
      "/tractors/nh-td5100-1.webp",
    ],
  },
  {
    id: 8,
    marka: "Başak",
    model: "BE 80",
    modelYili: "2015",
    guc: "80 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-be80-1.webp",
      "/tractors/basak-be80-2.webp",
      "/tractors/basak-be80-3.webp",
      "/tractors/basak-be80-4.webp",
      "/tractors/basak-be80-5.webp",
      "/tractors/basak-be80-6.webp",
      "/tractors/basak-be80-7.webp",
      "/tractors/basak-be80-8.webp",
      "/tractors/basak-be80-9.webp",
      "/tractors/basak-be80-10.webp",
      "/tractors/basak-be80-11.webp",
      "/tractors/basak-be80-12.webp",
    ],
  },
  {
    id: 9,
    marka: "John Deere",
    model: "5615",
    modelYili: "2005",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-green-50",
    textColor: "text-green-700",
    badge: "",
    fotolar: [
      "/tractors/jd-5615-1.webp",
      "/tractors/jd-5615-2.webp",
      "/tractors/jd-5615-3.webp",
      "/tractors/jd-5615-4.webp",
      "/tractors/jd-5615-5.webp",
      "/tractors/jd-5615-6.webp",
      "/tractors/jd-5615-7.webp",
      "/tractors/jd-5615-8.webp",
      "/tractors/jd-5615-9.webp",
    ],
  },
  {
    id: 10,
    marka: "Başak",
    model: "2055",
    modelYili: "2023",
    guc: "55 HP",
    saat: "185 saat",
    vites: "16+8",
    kuyrukMili: "540 / 540E d/d",
    kaldirmaKapasitesi: "2.700 kg",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2055-2.webp",
      "/tractors/basak-2055-1.webp",
      "/tractors/basak-2055-3.webp",
      "/tractors/basak-2055-4.webp",
      "/tractors/basak-2055-5.webp",
      "/tractors/basak-2055-6.webp",
      "/tractors/basak-2055-7.webp",
      "/tractors/basak-2055-8.webp",
      "/tractors/basak-2055-9.webp",
    ],
  },
  {
    id: 11,
    marka: "Başak",
    model: "2060",
    modelYili: "2017",
    guc: "60 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2060-1.webp",
      "/tractors/basak-2060-2.webp",
      "/tractors/basak-2060-3.webp",
      "/tractors/basak-2060-4.webp",
      "/tractors/basak-2060-5.webp",
      "/tractors/basak-2060-6.webp",
      "/tractors/basak-2060-7.webp",
      "/tractors/basak-2060-8.webp",
      "/tractors/basak-2060-9.webp",
    ],
  },
  {
    id: 12,
    marka: "Massey Ferguson",
    model: "3060 Phantom",
    modelYili: "2006",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-phantom-1.webp",
      "/tractors/mf-phantom-2.webp",
      "/tractors/mf-phantom-3.webp",
      "/tractors/mf-phantom-4.webp",
      "/tractors/mf-phantom-5.webp",
      "/tractors/mf-phantom-6.webp",
      "/tractors/mf-phantom-7.webp",
      "/tractors/mf-phantom-8.webp",
      "/tractors/mf-phantom-9.webp",
    ],
  },
  {
    id: 13,
    marka: "Tümosan",
    model: "8280 DT",
    modelYili: "1999",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-yellow-50",
    textColor: "text-yellow-700",
    badge: "",
    fotolar: [
      "/tractors/tumosan-8280dt-1.webp",
      "/tractors/tumosan-8280dt-2.webp",
      "/tractors/tumosan-8280dt-3.webp",
      "/tractors/tumosan-8280dt-4.webp",
      "/tractors/tumosan-8280dt-5.webp",
    ],
  },
  {
    id: 14,
    marka: "Landini",
    model: "7860",
    modelYili: "1999",
    guc: "78 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-purple-50",
    textColor: "text-purple-700",
    badge: "",
    fotolar: [
      "/tractors/landini-7860-1.webp",
      "/tractors/landini-7860-2.webp",
      "/tractors/landini-7860-3.webp",
      "/tractors/landini-7860-4.webp",
      "/tractors/landini-7860-5.webp",
    ],
  },
  {
    id: 15,
    marka: "Tümosan",
    model: "7170",
    modelYili: "2011",
    guc: "70 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-indigo-50",
    textColor: "text-indigo-700",
    badge: "",
    fotolar: [
      "/tractors/tumosan-7170-1.webp",
      "/tractors/tumosan-7170-2.webp",
      "/tractors/tumosan-7170-3.webp",
      "/tractors/tumosan-7170-4.webp",
      "/tractors/tumosan-7170-5.webp",
      "/tractors/tumosan-7170-6.webp",
    ],
  },
  {
    id: 16,
    marka: "Tümosan",
    model: "7070",
    modelYili: "2011",
    guc: "70 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-cyan-50",
    textColor: "text-cyan-700",
    badge: "",
    fotolar: [
      "/tractors/tumosan-7070-1.webp",
      "/tractors/tumosan-7070-2.webp",
      "/tractors/tumosan-7070-3.webp",
      "/tractors/tumosan-7070-4.webp",
      "/tractors/tumosan-7070-5.webp",
      "/tractors/tumosan-7070-6.webp",
    ],
  },
  {
    id: 17,
    marka: "John Deere",
    model: "5403",
    modelYili: "2005",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-green-50",
    textColor: "text-green-700",
    badge: "",
    fotolar: [
      "/tractors/jd-5403-1.webp",
      "/tractors/jd-5403-2.webp",
      "/tractors/jd-5403-3.webp",
      "/tractors/jd-5403-4.webp",
      "/tractors/jd-5403-5.webp",
      "/tractors/jd-5403-6.webp",
    ],
  },
  {
    id: 18,
    marka: "Massey Ferguson",
    model: "266 G",
    modelYili: "2004",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-266g-1.webp",
      "/tractors/mf-266g-2.webp",
      "/tractors/mf-266g-3.webp",
      "/tractors/mf-266g-4.webp",
    ],
  },
  {
    id: 19,
    marka: "Massey Ferguson",
    model: "240S",
    modelYili: "1998",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-240s-1.webp",
      "/tractors/mf-240s-2.webp",
      "/tractors/mf-240s-3.webp",
      "/tractors/mf-240s-4.webp",
      "/tractors/mf-240s-5.webp",
      "/tractors/mf-240s-6.webp",
      "/tractors/mf-240s-7.webp",
    ],
  },
  {
    id: 20,
    marka: "Captain",
    model: "24 HP",
    modelYili: "2025",
    guc: "24 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "Sıfır",
    renk: "bg-lime-50",
    textColor: "text-lime-700",
    badge: "",
    fotolar: [
      "/tractors/captain-24hp-1.webp",
      "/tractors/captain-24hp-2.webp",
      "/tractors/captain-24hp-3.webp",
      "/tractors/captain-24hp-4.webp",
      "/tractors/captain-24hp-5.webp",
      "/tractors/captain-24hp-6.webp",
      "/tractors/captain-24hp-7.webp",
      "/tractors/captain-24hp-8.webp",
    ],
  },
  {
    id: 21,
    marka: "Same",
    model: "Tiger 50",
    modelYili: "2010",
    guc: "50 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-amber-50",
    textColor: "text-amber-700",
    badge: "",
    fotolar: [
      "/tractors/same-tiger50-1.webp",
      "/tractors/same-tiger50-2.webp",
      "/tractors/same-tiger50-3.webp",
    ],
  },
  {
    id: 22,
    marka: "Başak",
    model: "2043 S",
    modelYili: "1998",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2043s-1.webp",
      "/tractors/basak-2043s-2.webp",
      "/tractors/basak-2043s-3.webp",
    ],
  },
  {
    id: 23,
    marka: "Fiat",
    model: "640",
    modelYili: "1977",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-640-1.webp",
      "/tractors/fiat-640-2.webp",
      "/tractors/fiat-640-3.webp",
    ],
  },
  {
    id: 24,
    marka: "Fiat",
    model: "480",
    modelYili: "1984",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-480-1.webp",
      "/tractors/fiat-480-2.webp",
      "/tractors/fiat-480-3.webp",
    ],
  },
  {
    id: 25,
    marka: "Steyr",
    model: "8073",
    modelYili: "1987",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-8073-1.webp",
      "/tractors/steyr-8073-2.webp",
      "/tractors/steyr-8073-3.webp",
    ],
  },
  {
    id: 26,
    marka: "Universal",
    model: "530",
    modelYili: "1996",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-violet-50",
    textColor: "text-violet-700",
    badge: "",
    fotolar: [
      "/tractors/universal-530-1.webp",
      "/tractors/universal-530-2.webp",
      "/tractors/universal-530-3.webp",
      "/tractors/universal-530-4.webp",
    ],
  },
  {
    id: 27,
    marka: "Universal",
    model: "445",
    modelYili: "1997",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-violet-50",
    textColor: "text-violet-700",
    badge: "",
    fotolar: [
      "/tractors/universal-445-1.webp",
      "/tractors/universal-445-2.webp",
      "/tractors/universal-445-3.webp",
      "/tractors/universal-445-4.webp",
      "/tractors/universal-445-5.webp",
    ],
  },
  {
    id: 28,
    marka: "Fiat",
    model: "A50",
    modelYili: "1998",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-a50-1.webp",
      "/tractors/fiat-a50-2.webp",
      "/tractors/fiat-a50-3.webp",
      "/tractors/fiat-a50-4.webp",
      "/tractors/fiat-a50-5.webp",
      "/tractors/fiat-a50-6.webp",
    ],
  },
  {
    id: 30,
    marka: "Başak",
    model: "2090",
    modelYili: "2016",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2090-1.webp",
      "/tractors/basak-2090-2.webp",
      "/tractors/basak-2090-3.webp",
      "/tractors/basak-2090-4.webp",
    ],
  },
  {
    id: 31,
    marka: "Fiat",
    model: "640",
    modelYili: "1982",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-640-1982-1.webp",
      "/tractors/fiat-640-1982-2.webp",
      "/tractors/fiat-640-1982-3.webp",
      "/tractors/fiat-640-1982-4.webp",
    ],
  },
  {
    id: 32,
    marka: "Captain",
    model: "26 HP Çift Çeker",
    modelYili: "2025",
    guc: "26 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "Sıfır",
    renk: "bg-lime-50",
    textColor: "text-lime-700",
    badge: "",
    fotolar: [
      "/tractors/captain-26hp-1.webp",
      "/tractors/captain-26hp-2.webp",
      "/tractors/captain-26hp-3.webp",
      "/tractors/captain-26hp-4.webp",
      "/tractors/captain-26hp-5.webp",
    ],
  },
  {
    id: 33,
    marka: "Massey Ferguson",
    model: "3060 Phantom",
    modelYili: "2005",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-phantom-2005-1.webp",
      "/tractors/mf-phantom-2005-2.webp",
      "/tractors/mf-phantom-2005-3.webp",
      "/tractors/mf-phantom-2005-4.webp",
      "/tractors/mf-phantom-2005-5.webp",
    ],
  },
  {
    id: 34,
    marka: "Taral",
    model: "855",
    modelYili: "2013",
    guc: "55 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-teal-50",
    textColor: "text-teal-700",
    badge: "",
    fotolar: [
      "/tractors/taral-855-1.webp",
      "/tractors/taral-855-2.webp",
      "/tractors/taral-855-3.webp",
      "/tractors/taral-855-4.webp",
      "/tractors/taral-855-5.webp",
      "/tractors/taral-855-6.webp",
    ],
  },
  {
    id: 35,
    marka: "Massey Ferguson",
    model: "265",
    modelYili: "1990",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-265-1.webp",
      "/tractors/mf-265-2.webp",
      "/tractors/mf-265-3.webp",
    ],
  },
  {
    id: 36,
    marka: "Massey Ferguson",
    model: "265",
    modelYili: "1991",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-265-1991-1.webp",
      "/tractors/mf-265-1991-2.webp",
      "/tractors/mf-265-1991-3.webp",
      "/tractors/mf-265-1991-4.webp",
      "/tractors/mf-265-1991-5.webp",
      "/tractors/mf-265-1991-6.webp",
      "/tractors/mf-265-1991-7.webp",
      "/tractors/mf-265-1991-8.webp",
      "/tractors/mf-265-1991-9.webp",
    ],
  },
  {
    id: 37,
    marka: "Massey Ferguson",
    model: "240",
    modelYili: "1982",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-240-1.webp",
      "/tractors/mf-240-2.webp",
      "/tractors/mf-240-3.webp",
      "/tractors/mf-240-4.webp",
    ],
  },
  {
    id: 38,
    marka: "Ford",
    model: "3000",
    modelYili: "1973",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/ford-3000-1.webp",
      "/tractors/ford-3000-2.webp",
      "/tractors/ford-3000-3.webp",
    ],
  },
  {
    id: 39,
    marka: "Ford",
    model: "5000",
    modelYili: "1969",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/ford-5000-1.webp",
      "/tractors/ford-5000-2.webp",
      "/tractors/ford-5000-3.webp",
    ],
  },
  {
    id: 40,
    marka: "Başak",
    model: "2073",
    modelYili: "2002",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2073-1.webp",
      "/tractors/basak-2073-2.webp",
      "/tractors/basak-2073-3.webp",
      "/tractors/basak-2073-4.webp",
      "/tractors/basak-2073-5.webp",
    ],
  },
  {
    id: 41,
    marka: "Başak",
    model: "2073",
    modelYili: "2000",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2073-2000-1.webp",
      "/tractors/basak-2073-2000-2.webp",
      "/tractors/basak-2073-2000-3.webp",
      "/tractors/basak-2073-2000-4.webp",
      "/tractors/basak-2073-2000-5.webp",
    ],
  },
  {
    id: 42,
    marka: "Steyr",
    model: "8073",
    modelYili: "1991",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-8073-1991-1.webp",
      "/tractors/steyr-8073-1991-2.webp",
      "/tractors/steyr-8073-1991-3.webp",
      "/tractors/steyr-8073-1991-4.webp",
      "/tractors/steyr-8073-1991-5.webp",
    ],
  },
  {
    id: 43,
    marka: "Steyr",
    model: "8073",
    modelYili: "1987",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-8073-1987-2-1.webp",
      "/tractors/steyr-8073-1987-2-2.webp",
      "/tractors/steyr-8073-1987-2-3.webp",
      "/tractors/steyr-8073-1987-2-4.webp",
      "/tractors/steyr-8073-1987-2-5.webp",
    ],
  },
  {
    id: 44,
    marka: "Steyr",
    model: "8073",
    modelYili: "1987",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-8073-1987-3-1.webp",
      "/tractors/steyr-8073-1987-3-2.webp",
      "/tractors/steyr-8073-1987-3-3.webp",
      "/tractors/steyr-8073-1987-3-4.webp",
      "/tractors/steyr-8073-1987-3-5.webp",
    ],
  },
  {
    id: 45,
    marka: "Steyr",
    model: "8053",
    modelYili: "1990",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-8053-1.webp",
      "/tractors/steyr-8053-2.webp",
      "/tractors/steyr-8053-3.webp",
      "/tractors/steyr-8053-4.webp",
    ],
  },
  {
    id: 46,
    marka: "Steyr",
    model: "768",
    modelYili: "1983",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-768-1.webp",
      "/tractors/steyr-768-2.webp",
      "/tractors/steyr-768-3.webp",
      "/tractors/steyr-768-4.webp",
    ],
  },
  {
    id: 47,
    marka: "John Deere",
    model: "5403 Kepçeli",
    modelYili: "2003",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-green-50",
    textColor: "text-green-700",
    badge: "",
    fotolar: [
      "/tractors/jd-5403-kepceli-1.webp",
      "/tractors/jd-5403-kepceli-2.webp",
      "/tractors/jd-5403-kepceli-3.webp",
      "/tractors/jd-5403-kepceli-4.webp",
      "/tractors/jd-5403-kepceli-5.webp",
      "/tractors/jd-5403-kepceli-6.webp",
      "/tractors/jd-5403-kepceli-7.webp",
    ],
  },
  {
    id: 48,
    marka: "Steyr",
    model: "768",
    modelYili: "1983",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-768-1983-2-1.webp",
      "/tractors/steyr-768-1983-2-2.webp",
      "/tractors/steyr-768-1983-2-3.webp",
      "/tractors/steyr-768-1983-2-4.webp",
      "/tractors/steyr-768-1983-2-5.webp",
      "/tractors/steyr-768-1983-2-6.webp",
    ],
  },
  {
    id: 49,
    marka: "Massey Ferguson",
    model: "285",
    modelYili: "1987",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-285-1.webp",
      "/tractors/mf-285-2.webp",
      "/tractors/mf-285-3.webp",
      "/tractors/mf-285-4.webp",
    ],
  },
  {
    id: 50,
    marka: "Hattat",
    model: "H45",
    modelYili: "2010",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-rose-50",
    textColor: "text-rose-700",
    badge: "",
    fotolar: [
      "/tractors/hattat-h45-1.webp",
      "/tractors/hattat-h45-2.webp",
      "/tractors/hattat-h45-3.webp",
      "/tractors/hattat-h45-4.webp",
      "/tractors/hattat-h45-5.webp",
      "/tractors/hattat-h45-6.webp",
    ],
  },
  {
    id: 51,
    marka: "Fiat",
    model: "70-56",
    modelYili: "1989",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-70-56-1.webp",
      "/tractors/fiat-70-56-2.webp",
      "/tractors/fiat-70-56-3.webp",
      "/tractors/fiat-70-56-4.webp",
      "/tractors/fiat-70-56-5.webp",
      "/tractors/fiat-70-56-6.webp",
    ],
  },
  {
    id: 52,
    marka: "Deutz-Fahr",
    model: "68",
    modelYili: "1979",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-fuchsia-50",
    textColor: "text-fuchsia-700",
    badge: "",
    fotolar: [
      "/tractors/deutz-68-1.webp",
      "/tractors/deutz-68-2.webp",
    ],
  },
  {
    id: 53,
    marka: "Fendt",
    model: "106",
    modelYili: "1976",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-lime-50",
    textColor: "text-lime-700",
    badge: "",
    fotolar: [
      "/tractors/fendt-106-1.webp",
      "/tractors/fendt-106-2.webp",
    ],
  },
  {
    id: 54,
    marka: "Ford",
    model: "3000",
    modelYili: "1975",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/ford-3000-1975-1.webp",
      "/tractors/ford-3000-1975-2.webp",
    ],
  },
  {
    id: 55,
    marka: "Steyr",
    model: "768",
    modelYili: "1981",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-768-1981-1.webp",
      "/tractors/steyr-768-1981-2.webp",
      "/tractors/steyr-768-1981-3.webp",
    ],
  },
  {
    id: 56,
    marka: "Steyr",
    model: "768",
    modelYili: "1983",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-emerald-50",
    textColor: "text-emerald-700",
    badge: "",
    fotolar: [
      "/tractors/steyr-768-1983-3-1.webp",
      "/tractors/steyr-768-1983-3-2.webp",
      "/tractors/steyr-768-1983-3-3.webp",
    ],
  },
  {
    id: 57,
    marka: "IMT",
    model: "-",
    modelYili: "1976",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-amber-50",
    textColor: "text-amber-700",
    badge: "",
    fotolar: [
      "/tractors/imt-1976-1.webp",
      "/tractors/imt-1976-2.webp",
      "/tractors/imt-1976-3.webp",
    ],
  },
  {
    id: 58,
    marka: "Enter",
    model: "444",
    modelYili: "1977",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-stone-50",
    textColor: "text-stone-700",
    badge: "",
    fotolar: [
      "/tractors/enter-444-1.webp",
      "/tractors/enter-444-2.webp",
    ],
  },
  {
    id: 59,
    marka: "Enter",
    model: "654",
    modelYili: "1975",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-stone-50",
    textColor: "text-stone-700",
    badge: "",
    fotolar: [
      "/tractors/enter-654-1.webp",
      "/tractors/enter-654-2.webp",
    ],
  },
  {
    id: 60,
    marka: "Fiat",
    model: "65-46",
    modelYili: "1987",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-65-46-1.webp",
      "/tractors/fiat-65-46-2.webp",
      "/tractors/fiat-65-46-3.webp",
      "/tractors/fiat-65-46-4.webp",
      "/tractors/fiat-65-46-5.webp",
    ],
  },
  {
    id: 61,
    marka: "Fiat",
    model: "480",
    modelYili: "1977",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-480-1977-1.webp",
      "/tractors/fiat-480-1977-2.webp",
      "/tractors/fiat-480-1977-3.webp",
      "/tractors/fiat-480-1977-4.webp",
      "/tractors/fiat-480-1977-5.webp",
    ],
  },
  {
    id: 62,
    marka: "New Holland",
    model: "TD65",
    modelYili: "2004",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/nh-td65-1.webp",
      "/tractors/nh-td65-2.webp",
      "/tractors/nh-td65-3.webp",
    ],
  },
  {
    id: 63,
    marka: "Valtra",
    model: "A75",
    modelYili: "2012",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/valtra-a75-2012-1.webp",
      "/tractors/valtra-a75-2012-2.webp",
      "/tractors/valtra-a75-2012-3.webp",
      "/tractors/valtra-a75-2012-4.webp",
    ],
  },
  {
    id: 64,
    marka: "Massey Ferguson",
    model: "3085 Phantom",
    modelYili: "2007",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-3085-phantom-1.webp",
      "/tractors/mf-3085-phantom-2.webp",
      "/tractors/mf-3085-phantom-3.webp",
      "/tractors/mf-3085-phantom-4.webp",
      "/tractors/mf-3085-phantom-5.webp",
    ],
  },
  {
    id: 65,
    marka: "Erkunt",
    model: "Kıymet 90 E",
    modelYili: "2013",
    guc: "90 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-teal-50",
    textColor: "text-teal-700",
    badge: "",
    fotolar: [
      "/tractors/erkunt-kiymet90e-1.webp",
      "/tractors/erkunt-kiymet90e-2.webp",
      "/tractors/erkunt-kiymet90e-3.webp",
      "/tractors/erkunt-kiymet90e-4.webp",
      "/tractors/erkunt-kiymet90e-5.webp",
    ],
  },
  {
    id: 66,
    marka: "Erkunt",
    model: "Nimet 70",
    modelYili: "2011",
    guc: "70 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-teal-50",
    textColor: "text-teal-700",
    badge: "",
    fotolar: [
      "/tractors/erkunt-nimet70-1.webp",
      "/tractors/erkunt-nimet70-2.webp",
      "/tractors/erkunt-nimet70-3.webp",
      "/tractors/erkunt-nimet70-4.webp",
      "/tractors/erkunt-nimet70-5.webp",
      "/tractors/erkunt-nimet70-6.webp",
    ],
  },
  {
    id: 67,
    marka: "New Holland",
    model: "60-66S",
    modelYili: "1999",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/nh-60-66s-1.webp",
      "/tractors/nh-60-66s-2.webp",
      "/tractors/nh-60-66s-3.webp",
      "/tractors/nh-60-66s-4.webp",
      "/tractors/nh-60-66s-5.webp",
    ],
  },
  {
    id: 68,
    marka: "Massey Ferguson",
    model: "3075 Phantom",
    modelYili: "2006",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-3075-phantom-1.webp",
      "/tractors/mf-3075-phantom-2.webp",
      "/tractors/mf-3075-phantom-3.webp",
      "/tractors/mf-3075-phantom-4.webp",
      "/tractors/mf-3075-phantom-5.webp",
    ],
  },
  {
    id: 69,
    marka: "Massey Ferguson",
    model: "285S",
    modelYili: "1994",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-285s-1.webp",
      "/tractors/mf-285s-2.webp",
      "/tractors/mf-285s-3.webp",
    ],
  },
  {
    id: 70,
    marka: "Massey Ferguson",
    model: "135",
    modelYili: "1976",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-135-1.webp",
      "/tractors/mf-135-2.webp",
      "/tractors/mf-135-3.webp",
    ],
  },
  {
    id: 71,
    marka: "Massey Ferguson",
    model: "285S",
    modelYili: "1993",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-285s-1993-1.webp",
      "/tractors/mf-285s-1993-2.webp",
      "/tractors/mf-285s-1993-3.webp",
      "/tractors/mf-285s-1993-4.webp",
    ],
  },
  {
    id: 72,
    marka: "Fiat",
    model: "60-56",
    modelYili: "1998",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-60-56-1.webp",
      "/tractors/fiat-60-56-2.webp",
      "/tractors/fiat-60-56-3.webp",
    ],
  },
  {
    id: 73,
    marka: "Fiat",
    model: "70-56",
    modelYili: "1996",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-70-56-1996-1.webp",
      "/tractors/fiat-70-56-1996-2.webp",
      "/tractors/fiat-70-56-1996-3.webp",
      "/tractors/fiat-70-56-1996-4.webp",
    ],
  },
  {
    id: 74,
    marka: "New Holland",
    model: "60-66S",
    modelYili: "2002",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-blue-50",
    textColor: "text-blue-700",
    badge: "",
    fotolar: [
      "/tractors/nh-60-66s-2002-1.webp",
      "/tractors/nh-60-66s-2002-2.webp",
      "/tractors/nh-60-66s-2002-3.webp",
    ],
  },
  {
    id: 75,
    marka: "Massey Ferguson",
    model: "285S",
    modelYili: "1998",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-285s-1998-1.webp",
      "/tractors/mf-285s-1998-2.webp",
      "/tractors/mf-285s-1998-3.webp",
      "/tractors/mf-285s-1998-4.webp",
      "/tractors/mf-285s-1998-5.webp",
    ],
  },
  {
    id: 76,
    marka: "Massey Ferguson",
    model: "398",
    modelYili: "1994",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-398-1.webp",
      "/tractors/mf-398-2.webp",
      "/tractors/mf-398-3.webp",
      "/tractors/mf-398-4.webp",
    ],
  },
  {
    id: 77,
    marka: "Fiat",
    model: "480",
    modelYili: "1983",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-sky-50",
    textColor: "text-sky-700",
    badge: "",
    fotolar: [
      "/tractors/fiat-480-1983-1.webp",
      "/tractors/fiat-480-1983-2.webp",
      "/tractors/fiat-480-1983-3.webp",
    ],
  },
  {
    id: 78,
    marka: "Kubota",
    model: "M7040",
    modelYili: "2016",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/kubota-m7040-1.webp",
      "/tractors/kubota-m7040-2.webp",
      "/tractors/kubota-m7040-3.webp",
      "/tractors/kubota-m7040-4.webp",
      "/tractors/kubota-m7040-5.webp",
    ],
  },
  {
    id: 79,
    marka: "Başak",
    model: "2060",
    modelYili: "2020",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2060-2020-1.webp",
      "/tractors/basak-2060-2020-2.webp",
      "/tractors/basak-2060-2020-3.webp",
      "/tractors/basak-2060-2020-4.webp",
      "/tractors/basak-2060-2020-5.webp",
      "/tractors/basak-2060-2020-6.webp",
    ],
  },
  {
    id: 80,
    marka: "Case",
    model: "JX70E",
    modelYili: "2024",
    guc: "70 HP",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/case-jx70e-1.webp",
      "/tractors/case-jx70e-2.webp",
      "/tractors/case-jx70e-3.webp",
      "/tractors/case-jx70e-4.webp",
      "/tractors/case-jx70e-5.webp",
      "/tractors/case-jx70e-6.webp",
      "/tractors/case-jx70e-7.webp",
      "/tractors/case-jx70e-8.webp",
    ],
  },
  {
    id: 81,
    marka: "Başak",
    model: "2075",
    modelYili: "2024",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "Sıfır",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2075-1.webp",
      "/tractors/basak-2075-2.webp",
      "/tractors/basak-2075-3.webp",
      "/tractors/basak-2075-4.webp",
      "/tractors/basak-2075-5.webp",
    ],
  },
  {
    id: 82,
    marka: "Başak",
    model: "5075",
    modelYili: "-",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "Sıfır",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-5075-1.webp",
      "/tractors/basak-5075-2.webp",
      "/tractors/basak-5075-3.webp",
      "/tractors/basak-5075-4.webp",
      "/tractors/basak-5075-5.webp",
      "/tractors/basak-5075-6.webp",
    ],
  },
  {
    id: 83,
    marka: "Başak",
    model: "2060",
    modelYili: "2015",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-red-50",
    textColor: "text-red-700",
    badge: "",
    fotolar: [
      "/tractors/basak-2060-2015-1.webp",
      "/tractors/basak-2060-2015-2.webp",
      "/tractors/basak-2060-2015-3.webp",
    ],
  },
  {
    id: 84,
    marka: "Massey Ferguson",
    model: "240S",
    modelYili: "2007",
    guc: "-",
    saat: "-",
    vites: "-",
    kuyrukMili: "-",
    kaldirmaKapasitesi: "-",
    durum: "2. El",
    renk: "bg-orange-50",
    textColor: "text-orange-700",
    badge: "",
    fotolar: [
      "/tractors/mf-240s-2007-1.webp",
      "/tractors/mf-240s-2007-2.webp",
      "/tractors/mf-240s-2007-3.webp",
    ],
  },
];
